name: Capture_The_Flag
version: 1.0
main: ori.capture_the_flag.Main
api-version: 1.16
description: A CTF(capture the flag) plugin by NotOri
commands:
  draw:
    description: draws the game zone
    usage: /<command>
  select:
    description: selects a team
  start:
    description: starts the game
